
name: deploy-staging
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: au-vps
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            
