# This workflow will:
# 1) install Python dependencies
# 2) run make test


name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.13"]

    # This allows a subsequently queued workflow run to interrupt previous runs
    concurrency:
      group: "${{ github.workflow }}-${{ matrix.python-version}}-${{ matrix.os }} @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          make install

      - name: Fix pyproject.toml license
        run: |
          echo "--- 🛠 Fixing pyproject.toml license ---"
          sed -i 's/license = "NoLicense"/license = "MIT"/' build/lex_db_api/pyproject.toml
          
      - name: Run tests
        shell: bash
        run: |
          make test
